version: "3"
services:
  gavel:
    container_name: gavel
    build: 
      context: .
      dockerfile: gavel.Dockerfile
    env_file: ./gavel/.env
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "sleep 5 && python initialize.py && python runserver.py"
    ports: 
      - 3000:3000
    volumes: 
      - ./gavel:/usr/app/src
    depends_on: 
      - pgadmin
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: gavel.Dockerfile
    env_file: ./gavel/.env
    command: "celery -A gavel:celery worker -E"
    user: nobody
    links:
        - redis
    volumes:
        - ./gavel:/usr/app/src:ro

  redis:
    image: redis:alpine
    hostname: redis
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  db:
    image: postgres:13
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    env_file: .env
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
        - pgadmin:/root/.pgadmin
        - ./servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'db:5432:postgres:admin:admin' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"

volumes:
  pgadmin: