version: "3"
services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./quill.Dockerfile
    environment: 
      - NODE_ENV=development
    ports: 
      - 3000:3000
    volumes: 
      - ./quill:/usr/app/src
    depends_on: 
      - mongo
      - mongo-express

  mongo:
    image: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
