version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    env_file: ../postgres/.env
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: ../postgres/.env
    volumes:
        - pgadmin:/root/.pgadmin
        - ../postgres/servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'db:5432:postgres:admin:admin' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"

  helpq:
    container_name: helpq
    build:
      context: ../..
      dockerfile: ./docker/helpq/Dockerfile
    env_file: .env
    ports: 
      - 3000:3000
    volumes: 
      - ../../helpqueue:/usr/app/src
    depends_on: 
      - db
      - pgadmin
    entrypoint: 
      - "/bin/bash"
      - "-c"
      - "sleep 5 && python manage.py db upgrade && yarn run dev"
    
volumes:
  pgadmin: